{
	"title": "进度监管",
	"subtitle1": "",
	"subtitle2": "",
	"isAddMoreIcon": "0",
	"moreUrl": "",
	"moduleType": "0",
	"barHisShowType": "0",
	"moduleCode": "",
	"blankTemplateConfig": {
		"slot": "",
		"isCloseBtn": false
	},
	"destailTypeTheme": "0",
	"apiType": "1",
	"url": "/landTransferSystem/selectJinDuJianGuanData",
	"urlName": "",
	"options": "POST",
	"keyArr": [
		{
			"key": "行政区域",
			"explain": "行政区域",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": "",
			"colFixed": "null"
		},
		{
			"key": "宗地位置",
			"explain": "宗地位置",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "用地性质",
			"explain": "用地性质",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "土地面积",
			"explain": "土地面积",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "竟得人",
			"explain": "竟得人",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "成交价格",
			"explain": "成交价格",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "溢价率",
			"explain": "溢价率",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "拟供应时间",
			"explain": "拟供应时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "公布公告时间",
			"explain": "公布公告时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "公布公告起止时间",
			"explain": "公布公告起止时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "竞标时间",
			"explain": "竞标时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "合同签订时间",
			"explain": "合同签订时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "合同约定开工时间",
			"explain": "合同约定开工时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": "",
			"cellRenderer": "function(colums,rowData){\nlet str=rowData[colums.key]\n\n                return str\n             }",
			"tipRenderer": null
		},
		{
			"key": "合同约定竣工时间",
			"explain": "合同约定竣工时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "合同编号",
			"explain": "合同编号",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "成交确认书编号",
			"explain": "成交确认书编号",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "土地出让金缴纳时间",
			"explain": "土地出让金缴纳时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "价款金额",
			"explain": "价款金额",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "签订日期",
			"explain": "签订日期",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "土地权属登记时间",
			"explain": "土地权属登记时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "建设用地规划许可时间",
			"explain": "建设用地规划许可时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "建设工程规划许可时间",
			"explain": "建设工程规划许可时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "建筑工程施工许可时间",
			"explain": "建筑工程施工许可时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "房屋预售时间",
			"explain": "房屋预售时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		},
		{
			"key": "竣工验收实际时间",
			"explain": "竣工验收实际时间",
			"dw": "",
			"width": 120,
			"isShow": true,
			"isCruxKey": false,
			"isMapKey": false,
			"ischartsTitle": false,
			"ischartsShow": false,
			"zBgColor": ""
		}
	],
	"tableHeaderConfig": {
		"hierarchy": 2,
		"headerSetting": [
			{
				"label": "表头",
				"id": "0",
				"hierarchy": 0,
				"children": [
					{
						"label": "基本情况",
						"key": "",
						"hierarchy": 1,
						"id": "0-1",
						"children": [
							{
								"label": "行政区域",
								"key": "行政区域",
								"hierarchy": 1,
								"id": "0-5",
								"children": [],
								"explain": "行政区域",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": "",
								"colFixed": "null"
							},
							{
								"label": "宗地位置",
								"key": "宗地位置",
								"hierarchy": 2,
								"id": "0-1-5",
								"children": [],
								"explain": "宗地位置",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "用地性质",
								"key": "用地性质",
								"hierarchy": 2,
								"id": "0-1-2",
								"children": [],
								"explain": "用地性质",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "土地面积",
								"key": "土地面积",
								"hierarchy": 2,
								"id": "0-1-3",
								"children": [],
								"explain": "土地面积",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							}
						],
						"explain": "",
						"width": 120,
						"dw": "",
						"isCruxKey": false,
						"isShow": true,
						"isMapKey": false,
						"ischartsTitle": false,
						"ischartsShow": false,
						"zBgColor": ""
					},
					{
						"label": "溢价率",
						"key": "",
						"hierarchy": 1,
						"id": "0-2",
						"children": [
							{
								"label": "竟得人",
								"key": "竟得人",
								"hierarchy": 2,
								"id": "0-2-1",
								"children": [],
								"explain": "竟得人",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "成交价格",
								"key": "成交价格",
								"hierarchy": 2,
								"id": "0-2-2",
								"children": [],
								"explain": "成交价格",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "溢价率",
								"key": "溢价率",
								"hierarchy": 2,
								"id": "0-2-3",
								"children": [],
								"explain": "溢价率",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "拟供应时间",
								"key": "拟供应时间",
								"hierarchy": 2,
								"id": "0-2-4",
								"children": [],
								"explain": "拟供应时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "公布公告时间",
								"key": "公布公告时间",
								"hierarchy": 2,
								"id": "0-2-5",
								"children": [],
								"explain": "公布公告时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "公布公告起止时间",
								"key": "公布公告起止时间",
								"hierarchy": 2,
								"id": "0-2-6",
								"children": [],
								"explain": "公布公告起止时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "竞标时间",
								"key": "竞标时间",
								"hierarchy": 2,
								"id": "0-2-7",
								"children": [],
								"explain": "竞标时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							}
						],
						"explain": "",
						"width": 120,
						"dw": "",
						"isCruxKey": false,
						"isShow": true,
						"isMapKey": false,
						"ischartsTitle": false,
						"ischartsShow": false,
						"zBgColor": ""
					},
					{
						"label": "合同阶段",
						"key": "",
						"hierarchy": 1,
						"id": "0-3",
						"children": [
							{
								"label": "合同签订时间",
								"key": "合同签订时间",
								"hierarchy": 2,
								"id": "0-3-1",
								"children": [],
								"explain": "合同签订时间",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "合同约定开工时间",
								"key": "约定动工时间",
								"hierarchy": 2,
								"id": "0-3-7",
								"children": [],
								"explain": "约定动工时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "合同约定竣工时间",
								"key": "合同约定竣工时间",
								"hierarchy": 2,
								"id": "0-3-7",
								"children": [],
								"explain": "合同约定竣工时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "合同编号",
								"key": "合同编号",
								"hierarchy": 2,
								"id": "0-3-2",
								"children": [],
								"explain": "合同编号",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "成交确认书编号",
								"key": "成交确认书编号",
								"hierarchy": 2,
								"id": "0-3-3",
								"children": [],
								"explain": "成交确认书编号",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "土地出让金缴纳时间",
								"key": "土地出让金缴纳时间",
								"hierarchy": 2,
								"id": "0-3-4",
								"children": [],
								"explain": "土地出让金缴纳时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "价款金额",
								"key": "价款金额",
								"hierarchy": 2,
								"id": "0-3-5",
								"children": [],
								"explain": "价款金额",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "签订日期",
								"key": "签订日期",
								"hierarchy": 2,
								"id": "0-3-8",
								"children": [],
								"explain": "签订日期",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							}
						],
						"explain": "",
						"width": 120,
						"dw": "",
						"isCruxKey": false,
						"isShow": true,
						"isMapKey": false,
						"ischartsTitle": false,
						"ischartsShow": false,
						"zBgColor": ""
					},
					{
						"label": "供后",
						"key": "",
						"hierarchy": 1,
						"id": "0-4",
						"children": [
							{
								"label": "土地权属登记时间",
								"key": "土地权属登记时间",
								"hierarchy": 2,
								"id": "0-4-1",
								"children": [],
								"explain": "土地权属登记时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "建设用地规划许可时间",
								"key": "建设用地规划许可时间",
								"hierarchy": 2,
								"id": "0-4-2",
								"children": [],
								"explain": "建设用地规划许可时间",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "建设工程规划许可时间",
								"key": "建设工程规划许可时间",
								"hierarchy": 2,
								"id": "0-4-3",
								"children": [],
								"explain": "建设工程规划许可时间",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "建筑工程施工许可时间",
								"key": "建筑工程施工许可时间",
								"hierarchy": 2,
								"id": "0-4-4",
								"children": [],
								"explain": "建筑工程施工许可时间",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "房屋预售时间",
								"key": "房屋预售时间",
								"hierarchy": 2,
								"id": "0-4-5",
								"children": [],
								"explain": "房屋预售时间",
								"width": 120,
								"dw": "",
								"isCruxKey": false,
								"isShow": true,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							},
							{
								"label": "竣工验收实际时间",
								"key": "竣工验收实际时间",
								"hierarchy": 2,
								"id": "0-4-6",
								"children": [],
								"explain": "竣工验收实际时间",
								"dw": "",
								"width": 120,
								"isShow": true,
								"isCruxKey": false,
								"isMapKey": false,
								"ischartsTitle": false,
								"ischartsShow": false,
								"zBgColor": ""
							}
						],
						"explain": "",
						"width": 120,
						"dw": "",
						"isCruxKey": false,
						"isShow": true,
						"isMapKey": false,
						"ischartsTitle": false,
						"ischartsShow": false,
						"zBgColor": ""
					}
				]
			}
		]
	},
	"operateButton": [],
	"paramConfig": [],
	"destailsTableLabelWidth": 100,
	"detailsTableAll": [],
	"iframeAll": {
		"iframeType": "0",
		"iframeId": "",
		"iframeUrl": "http://23.36.250.99:666/views/showmap.html?callid=10129"
	},
	"height": 98.56,
	"width": 99.44,
	"top": 0.78,
	"left": 0.26,
	"defaultParameters": "",
	"zindex": "15",
	"displayMode": "table",
	"titleShow": "0",
	"submodule": "0",
	"menuTapAll": {
		"isMenuTap": "0",
		"menuTapKey": "",
		"menuCodeKey": ""
	},
	"clickToShow": "row",
	"isLinkMap": "0",
	"mapPosition": "0",
	"isPage": "1",
	"mask": "0",
	"pageSize": 20,
	"isDestail": "0",
	"isDrafting": false,
	"viewId": "dd226071-ba89-be4a-9a2d-a21f3e3b90f3",
	"tableOtherConfig": {
		"tableType": "0",
		"onlyKey": "",
		"childKey": "children"
	},
	"isHeaderHide": false,
	"isModuleClose": true
}